name: Automated Checks
run-name: Automated checks on pull-request and main push
on:
  push:
    branches: [main]
  pull_request: {}
permissions:
  contents: read
jobs:
  syntax:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.4]
    name: PHP ${{ matrix.php }} Syntax
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: check syntax
        run: jobs/php-syntax.sh
  test:
    name: Standards + Analysis
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: dependencies
        uses: php-actions/composer@v6
        with:
          args: --no-scripts
      - name: standards
        run: jobs/code-standards.sh
      - name: analysis
        run: jobs/static-analysis.sh
